# Generated by Django 6.0 on 2025-12-17 00:06

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('lugar', models.CharField(max_length=50)),
                ('recaudacion_objetivo', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('recaudacion_actual', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('descripcion', models.CharField(max_length=500)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='eventos/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('menu', models.CharField(max_length=1000)),
                ('num_mesas', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('num_asientos', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_por_persona', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'Cena',
                'verbose_name_plural': 'Cenas',
            },
        ),
        migrations.CreateModel(
            name='Concierto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('lugar', models.CharField(max_length=50)),
                ('recaudacion_objetivo', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('recaudacion_actual', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('descripcion', models.CharField(max_length=500)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='eventos/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('max_asistentes', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('num_filas', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('num_asientos', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_entrada', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'Concierto',
                'verbose_name_plural': 'Conciertos',
            },
        ),
        migrations.CreateModel(
            name='Marcha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('lugar', models.CharField(max_length=50)),
                ('recaudacion_objetivo', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('recaudacion_actual', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('descripcion', models.CharField(max_length=500)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='eventos/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('recorrido', models.CharField(max_length=200)),
                ('precio_inscripcion', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_participantes', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'verbose_name': 'Marcha',
                'verbose_name_plural': 'Marchas',
            },
        ),
        migrations.CreateModel(
            name='Rifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('lugar', models.CharField(max_length=50)),
                ('recaudacion_objetivo', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('recaudacion_actual', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('descripcion', models.CharField(max_length=500)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='eventos/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('premio', models.CharField(max_length=200)),
                ('boletos_vendidos', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('precio_boleto', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_boletos', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'verbose_name': 'Rifa',
                'verbose_name_plural': 'Rifas',
            },
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_mesa', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('asignaciones', models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('evento_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesas', to='eventos.cena')),
            ],
            options={
                'ordering': ['num_mesa'],
                'unique_together': {('num_mesa', 'evento_fk')},
            },
        ),
        migrations.CreateModel(
            name='EntradaCena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('telefono', models.CharField(blank=True, default='', max_length=20)),
                ('usado', models.BooleanField(default=False)),
                ('fecha_compra', models.DateTimeField(default=django.utils.timezone.now)),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='eventos.mesa')),
            ],
            options={
                'verbose_name': 'Entrada de Cena',
                'verbose_name_plural': 'Entradas de Cena',
            },
        ),
        migrations.CreateModel(
            name='EntradaConcierto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('telefono', models.CharField(blank=True, default='', max_length=20)),
                ('usado', models.BooleanField(default=False)),
                ('fecha_compra', models.DateTimeField(default=django.utils.timezone.now)),
                ('fila', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('asiento', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('concierto_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='eventos.concierto')),
            ],
            options={
                'verbose_name': 'Entrada de Concierto',
                'verbose_name_plural': 'Entradas de Concierto',
                'ordering': ['fila', 'asiento'],
                'unique_together': {('fila', 'asiento', 'concierto_fk')},
            },
        ),
        migrations.CreateModel(
            name='Dorsal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('telefono', models.CharField(blank=True, default='', max_length=20)),
                ('usado', models.BooleanField(default=False)),
                ('fecha_compra', models.DateTimeField(default=django.utils.timezone.now)),
                ('num', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('talla', models.CharField(choices=[('XXS', 'Extra Extra Small'), ('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Extra Extra Large')], max_length=3)),
                ('marcha_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dorsales', to='eventos.marcha')),
            ],
            options={
                'verbose_name': 'Dorsal de Marcha',
                'verbose_name_plural': 'Dorsales de Marcha',
                'ordering': ['num'],
                'unique_together': {('num', 'marcha_fk')},
            },
        ),
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('telefono', models.CharField(blank=True, default='', max_length=20)),
                ('usado', models.BooleanField(default=False)),
                ('fecha_compra', models.DateTimeField(default=django.utils.timezone.now)),
                ('num', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('rifa_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletos', to='eventos.rifa')),
            ],
            options={
                'verbose_name': 'Boleto de Rifa',
                'verbose_name_plural': 'Boletos de Rifa',
                'ordering': ['num'],
                'unique_together': {('num', 'rifa_fk')},
            },
        ),
    ]
