# Generated by Django 6.0 on 2025-12-16 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('lugar', models.CharField(max_length=50)),
                ('recaudacion_objetivo', models.IntegerField()),
                ('descripcion', models.CharField(max_length=500)),
                ('menu', models.CharField(max_length=1000)),
                ('num_mesas', models.IntegerField()),
                ('num_asientos', models.SmallIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dorsal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('usado', models.BooleanField()),
                ('num', models.IntegerField()),
                ('talla', models.CharField(choices=[('XXS', 'Extra Extra Small'), ('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXl', 'Extra Extra Large')], max_length=3)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EntradaConcierto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('usado', models.BooleanField()),
                ('fila', models.SmallIntegerField()),
                ('asiento', models.BigIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Marcha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('lugar', models.CharField(max_length=50)),
                ('recaudacion_objetivo', models.IntegerField()),
                ('descripcion', models.CharField(max_length=500)),
                ('recorrido', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('lugar', models.CharField(max_length=50)),
                ('recaudacion_objetivo', models.IntegerField()),
                ('descripcion', models.CharField(max_length=500)),
                ('premio', models.CharField(max_length=200)),
                ('boletos_vendidos', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_mesa', models.BigIntegerField()),
                ('asignaciones', models.SmallIntegerField()),
                ('evento_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.cena')),
            ],
        ),
        migrations.CreateModel(
            name='EntradaCena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('usado', models.BooleanField()),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.mesa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('usado', models.BooleanField()),
                ('num', models.IntegerField()),
                ('rifa_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.rifa')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
