# Generated by Django 6.0 on 2025-12-16 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concierto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('lugar', models.CharField(max_length=50)),
                ('recaudacion_objetivo', models.IntegerField()),
                ('descripcion', models.CharField(max_length=500)),
                ('max_asistentes', models.IntegerField()),
                ('num_filas', models.SmallIntegerField()),
                ('num_asientos', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
